services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.4.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema2
    ports:
      - 3307:3306
    #volumes:
    #- ./sql/shopapp.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - cinema-network

  phpmyadmin8-container:
    #intel host
    image: phpmyadmin/phpmyadmin
    #image: arm64v8/phpmyadmin #choose this if you are running on Mac Apple Silicon(M1, M2,...)
    container_name: phpmyadmin8-container
    restart: always
    depends_on:
      - mysql8-container
    ports:
      - "8100:80" #port mapping
    environment:
      PMA_HOST: mysql8-container #phpMyAdmin Host, PMA = PHP My Amin
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    networks:
      - cinema-network

  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379" # Port mapping for Redis, you can change the host port as needed
    volumes:
      - ./redis-data:/data # Mount a volume for Redis data persistence
    networks:
      - cinema-network

  cinema-backend-container:
    container_name: cinema-backend-container
    build:
        context: .
        dockerfile: DockerfileSpringCinema

    ports:
      - 8099:8008
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8-container:3306/cinema2?serverTimezone=UTC&allowPublicKeyRetrieval=true
      MYSQL_ROOT_PASSWORD: root
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
    networks:
        - cinema-network
    depends_on:
        - mysql8-container
#        - redis-container

networks:
  cinema-network:
    name: cinema-network
    driver: bridge


#  docker-compose -f ./deployment.yaml up -d mysql8-container
#  docker-compose -f ./deployment.yaml up -d phpmyadmin8-container
#  docker-compose -f ./deployment.yaml up -d redis-container