spring:
  application:
    name: cinema-back

  datasource:
    url: "jdbc:mysql://localhost:3306/cinema2"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: root
      password: root

server:
  port: 8080

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  expiration: "3600000000"
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type: trace
