spring:
  application:
    name: cinema-back
  data:
    redis:
      use-redis-cache: false
      port: 6379
      host: 127.0.0.1
      connect-timeout: 30000
      lettuce:
        pool:
            max-active: 10
            max-idle: 5
            min-idle: 5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/cinema2?useSSL=false&serverTimezone=UTC
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password:
    hikari:
        maximum-pool-size: 20
        minimum-idle: 5
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
  #    show-sql: true
    properties:
      format_sql: true
      use_sql_comments: true

  security:
    user:
      name: root
      password: root

server:
  port: 8080
  tomcat:
    accept-count: 20000
    threads:
      max: 200
      min-spare: 50

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  expiration: "3600000000"
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type: trace
