spring:
  application:
    name: cinema-back
  data:
    redis:
      use-redis-cache: false
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:127.0.0.1}
      connect-timeout: 30000
      lettuce:
        pool:
            max-active: 10
            max-idle: 5
            min-idle: 5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/cinema2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root}
    hikari:
        maximum-pool-size: 20
        minimum-idle: 5
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
  #    show-sql: true
    properties:
      format_sql: true
      use_sql_comments: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#            jdbc:
#            time_zone: UTC

  security:
    user:
      name: root
      password: root

server:
  port: 8008
  tomcat:
    accept-count: 20000
    threads:
      max: 200
      min-spare: 50

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  expiration: "3600000000"
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type: trace

resilience4j:
  circuit breaker:
    instances:
      cinemaServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  ratelimiter:
    instances:
      cinemaServiceRL:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
#  retry:
#    instances:
#        cinemaService:
#      maxAttempts: 3
#      waitDuration: 10s
#      enableExponentialBackoff: true
#      exponentialBackoffMultiplier: 2
#      retryExceptions:
#        - com.dotnt.cinemaback.exception.AppException
#        - org.springframework.web.client.HttpServerErrorException
#        - java.io.IOException
#      ignoreExceptions:
#        - io.github.robwin.exception.BusinessException

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true
    endpoint:
      metrics:
        enabled: true
      prometheus:
        enabled: true